### ISSUE TITLE
Google doc got taken down

### ISSUE THREAD

**Issue by JMcrafter26** [vidio-boy/Eaglercraft1.8.8#1]
the google doc linkt to this page got taken down

**Comment by WithermaskScool** [comment]
true

**Comment by vidio-boy** [comment]
Yeah I was inactive for awhile. I'm working on fixing stuff the next two weeks.
________________________________

**Comment by vidio-boy** [comment]
> the google doc linkt to this page got taken down

Done! It was easier than I thoght, I just needed to use the Wayback Machine.
